### ISSUE TITLE
Discussion: Midi features

### ISSUE THREAD

**Issue by georgkrause** [openAVproductions/openAV-Luppp#139]
Here is a list of Midi features, that are missing at the moment:

- [ ] Cear Clip Midi Binding ( #134 )
- [ ] Displaying the beat on a midi controller ( #124 )
- [ ] improve sceneLaunch output Bindings ( #78 and #127)

**Comment by harryhaaren** [comment]
Removing milestone for now - but really Mappa is the answer to a lot of these feature-requests. Please discuss before putting any developer time into the above issues.
